'use client'

import { X, Sparkles, Clock, CheckCircle, AlertCircle, FileText } from 'lucide-react'

export default function NoteModal({ open, onClose, doc }) {
  if (!open || !doc) return null

  const taskName = doc.task?.taskName ?? 'Untitled Task'
  const subject  = doc.task?.subject  ?? ''
  const label    = `${subject ? subject + ' – ' : ''}${taskName}`

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/30 backdrop-blur-sm px-4"
      onClick={onClose}
    >
      <div
        className="bg-white rounded-2xl shadow-2xl w-full max-w-lg p-6 flex flex-col gap-4"
        onClick={e => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-start justify-between">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-lg bg-pink-50 flex items-center justify-center">
              <Sparkles className="w-4 h-4 text-[#8B1A4A]" />
            </div>
            <div>
              <p className="text-xs text-gray-400 font-medium">AI Feedback</p>
              <p className="text-sm font-bold text-gray-800 truncate max-w-[300px]">{label}</p>
            </div>
          </div>
          <button onClick={onClose} className="p-1.5 rounded-lg hover:bg-gray-100 text-gray-400">
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Status + date */}
        <div className="flex items-center gap-2">
          <span className={`flex items-center gap-1 text-[10px] font-bold px-2 py-0.5 rounded-full ${
            doc.ai_verified ? 'bg-green-50 text-green-600' : 'bg-amber-50 text-amber-600'
          }`}>
            {doc.ai_verified
              ? <><CheckCircle className="w-3 h-3" /> REVIEWED</>
              : <><AlertCircle className="w-3 h-3" /> WAITING REVIEW</>
            }
          </span>
          {doc.created_at && (
            <span className="flex items-center gap-1 text-[11px] text-gray-400">
              <Clock className="w-3 h-3" />
              {new Date(doc.created_at).toLocaleDateString('en-US', {
                year: 'numeric', month: 'short', day: 'numeric'
              })}
            </span>
          )}
        </div>

        {/* Document review section */}
        <div className="flex flex-col gap-2">
          <div className="flex items-center gap-2">
            <FileText className="w-3.5 h-3.5 text-gray-400" />
            <p className="text-xs font-bold text-gray-600 uppercase tracking-wider">Document Review</p>
          </div>
          <div className={`rounded-xl p-4 border ${
            doc.ai_verified
              ? 'bg-green-50 border-green-100'
              : 'bg-amber-50 border-amber-100'
          }`}>
            <p className="text-sm text-gray-700 leading-relaxed">
              {doc.ai_feedback ?? 'No feedback available yet.'}
            </p>
          </div>
        </div>

        {/* Session note section — shown if doc has a session narrative */}
        {doc.sessionNarrative && (
          <div className="flex flex-col gap-2">
            <div className="flex items-center gap-2">
              <Sparkles className="w-3.5 h-3.5 text-gray-400" />
              <p className="text-xs font-bold text-gray-600 uppercase tracking-wider">Session Summary</p>
            </div>
            <div className="bg-gray-50 rounded-xl p-4 border border-gray-100">
              <p className="text-sm text-gray-700 leading-relaxed">
                {doc.sessionNarrative}
              </p>
            </div>
          </div>
        )}

        {/* Footer */}
        <div className="flex items-center justify-between pt-1">
          <p className="text-[11px] text-gray-400 flex items-center gap-1">
            <Sparkles className="w-3 h-3" /> Generated by Basira AI
          </p>
          <button onClick={onClose} className="text-xs font-semibold text-[#8B1A4A] hover:underline">
            Close
          </button>
        </div>
      </div>
    </div>
  )
}